### ISSUE TITLE
Evaluation tarkistusfunktio

### ISSUE THREAD

**Issue by styxnix** [sakuexe/insikoorit#6]

**Comment by sakuexe** [comment]
# huomautus

päivitin juuri tämän päivän aikana annetun ohjeistuksen perusteella modelin training tiedostot. eli kannattaa tehdä igt pull kun ehtii, sillä koodi on muuttunut.

**Comment by sakuexe** [comment]
Aleksi sai aikaisemmin evaluation funktion valmiiksi, joten sain sen lisättyä web appiin.
