### ISSUE TITLE
Kaikki koittaa etsiä hyvää modelia oppari hommaan

### ISSUE THREAD

**Issue by styxnix** [sakuexe/insikoorit#7]

**Comment by sakuexe** [comment]
- [google-bert/bert-base-multilingual-uncased](https://huggingface.co/google-bert/bert-base-multilingual-cased)
- pelkkä translator: [facebook/mbart-large-50-one-to-many-mmt](https://huggingface.co/facebook/mbart-large-50-one-to-many-mmt)
